# Generated by Django 2.2.16 on 2021-02-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='номер (лучше не трогать)')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('text', models.TextField(verbose_name='текст')),
                ('icon', models.CharField(max_length=300, verbose_name='имя иконки(вместе с расширением)')),
                ('location', models.CharField(max_length=1, verbose_name='п или л')),
            ],
        ),
        migrations.CreateModel(
            name='Сontacts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='номер (лучше не трогать)')),
                ('contact', models.CharField(max_length=300, verbose_name='контакт')),
                ('icon', models.CharField(max_length=300, verbose_name='имя иконки(вместе с расширением)')),
            ],
        ),
    ]
