# Generated by Django 2.2.16 on 2021-03-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_css', models.CharField(max_length=500, verbose_name='версия css')),
                ('version_js', models.CharField(max_length=500, verbose_name='версия js')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версия',
            },
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Секции', 'verbose_name_plural': 'Секции'},
        ),
        migrations.AlterModelOptions(
            name='buttompanel',
            options={'verbose_name': 'Нижняя панель', 'verbose_name_plural': 'Нижняя панель'},
        ),
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'Шапка', 'verbose_name_plural': 'Шапка'},
        ),
        migrations.AlterModelOptions(
            name='сontacts',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterField(
            model_name='header',
            name='icon_header',
            field=models.ImageField(upload_to='media/image/', verbose_name='фотка в шапке'),
        ),
    ]
