# Generated by Django 2.2.16 on 2021-03-27 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210325_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='version_js',
        ),
    ]
