# Generated by Django 3.2.3 on 2021-05-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_style_version_js'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='keyword',
            field=models.CharField(default='project', max_length=200, verbose_name='ключевое слово'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buttompanel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='header',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='style',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
