# Generated by Django 3.2.3 on 2021-05-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='icon',
            field=models.FileField(default='/shpargalki/media/image/logo-pc.jpg', upload_to='media/image/', verbose_name='иконкa'),
            preserve_default=False,
        ),
    ]
