# Generated by Django 3.2.3 on 2021-05-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0002_content_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'контент', 'verbose_name_plural': 'контент'},
        ),
    ]
